from tkinter import *
w = Tk()
w.geometry('300x300')
w.title('registration form')
l=Label(text = "Registration Form")
l.pack()
name=Label(text = 'Name:')
name.pack()
nameentry = Entry().pack()
ph_no=Label(text = 'Ph_no:')
ph_no.pack()
ph_noentry = Entry().pack()
gender=Label(text = 'Gender:')
gender.pack()
genderentry = Entry().pack()
email=Label(text = 'E-mail:')
email.pack()
emailentry = Entry().pack()
b = Button(text="Submit",bg="yellow",fg="red",activebackground='orange')
b.pack()

w.mainloop()