# l=open(r"D:\phythonclassfiles\forcheck.txt",'w+')
# l.write("Nikhil")
# l.write(" Sam Ninan")
# l.seek(0)
# s=l.read()
# print(s)
# l.close()
l=open("listfile.txt",'w+')
l.write("nikhil sam")
l.seek(0)
a=l.read()
print (type(a))
l.close()